const HUBSPOT_BASE_URL = process.env.HUBSPOT_BASE_URL || "https://api.hubapi.com";

const propertyDefinitions = {
  contacts: [
    enumProperty("deal_threads_authority_signal", "Deal Threads Authority Signal", "Contact's buying authority captured by Deal Threads.", [
      ["Decision owner", "decision_owner"],
      ["Influencer", "influencer"],
      ["Researcher", "researcher"],
      ["Consultant", "consultant"],
      ["Unknown", "unknown"]
    ]),
    enumProperty("deal_threads_timeline", "Deal Threads Timeline", "Timeline captured by the Deal Threads widget.", [
      ["This week", "this_week"],
      ["This month", "this_month"],
      ["This quarter", "this_quarter"],
      ["Later this year", "later_this_year"],
      ["Researching", "researching"],
      ["Unknown", "unknown"]
    ]),
    enumProperty("deal_threads_budget_status", "Deal Threads Budget Status", "Budget readiness captured by Deal Threads.", [
      ["Approved", "approved"],
      ["Likely", "likely"],
      ["Building case", "building_case"],
      ["None", "none"],
      ["Unknown", "unknown"]
    ]),
    enumProperty("deal_threads_budget_range", "Deal Threads Budget Range", "Budget range captured by Deal Threads.", [
      ["Under $10K", "under_10k"],
      ["$10K-$30K", "10k_30k"],
      ["$30K-$60K", "30k_60k"],
      ["$60K+", "60k_plus"],
      ["Unknown", "unknown"]
    ]),
    textAreaProperty("deal_threads_business_need", "Deal Threads Business Need", "Visitor-provided business need captured by Deal Threads."),
    textAreaProperty("deal_threads_pain_point", "Deal Threads Pain Point", "Primary pain point inferred or captured by Deal Threads."),
    numberProperty("deal_threads_icp_score", "Deal Threads ICP Score", "Deal Threads ICP score from 0 to 100."),
    enumProperty("deal_threads_priority", "Deal Threads Priority", "Lead priority assigned by Deal Threads.", [
      ["High", "high"],
      ["Medium", "medium"],
      ["Low", "low"],
      ["Manual review", "manual_review"]
    ]),
    textAreaProperty("deal_threads_next_action", "Deal Threads Next Action", "Recommended sales action generated by Deal Threads."),
    stringProperty("deal_threads_source_page", "Deal Threads Source Page", "Source page where the Deal Threads widget conversation started."),
    stringProperty("deal_threads_utm_campaign", "Deal Threads UTM Campaign", "UTM campaign captured by Deal Threads."),
    enumProperty("deal_threads_sync_status", "Deal Threads Sync Status", "Current Deal Threads sync status.", [
      ["Pending", "pending"],
      ["Synced", "synced"],
      ["Failed", "failed"],
      ["Stubbed", "stubbed"]
    ]),
    stringProperty("deal_threads_lead_profile_id", "Deal Threads Lead Profile ID", "Internal Deal Threads lead profile ID."),
    stringProperty("deal_threads_conversation_id", "Deal Threads Conversation ID", "Internal Deal Threads conversation ID."),
    stringProperty("deal_threads_last_synced_at", "Deal Threads Last Synced At", "Last time Deal Threads synced this record.")
  ],
  companies: [
    stringProperty("deal_threads_employee_range", "Deal Threads Employee Range", "Employee range captured or enriched by Deal Threads."),
    stringProperty("deal_threads_revenue_range", "Deal Threads Revenue Range", "Revenue range captured or enriched by Deal Threads."),
    textAreaProperty("deal_threads_tech_stack", "Deal Threads Tech Stack", "Detected or visitor-provided technology stack."),
    textAreaProperty("deal_threads_recent_funding", "Deal Threads Recent Funding", "Recent funding context captured or enriched by Deal Threads."),
    stringProperty("deal_threads_icp_segment", "Deal Threads ICP Segment", "ICP segment assigned by Deal Threads."),
    enumProperty("deal_threads_enrichment_status", "Deal Threads Enrichment Status", "Status of Deal Threads enrichment.", [
      ["Completed", "completed"],
      ["Fallback", "fallback"],
      ["Failed", "failed"],
      ["Manual review", "manual_review"],
      ["Unavailable", "unavailable"]
    ]),
    numberProperty("deal_threads_enrichment_confidence", "Deal Threads Enrichment Confidence", "Confidence score for enriched context.")
  ],
  deals: [
    enumProperty("deal_threads_priority", "Deal Threads Priority", "Deal priority assigned by Deal Threads.", [
      ["High", "high"],
      ["Medium", "medium"],
      ["Low", "low"],
      ["Manual review", "manual_review"]
    ]),
    numberProperty("deal_threads_icp_score", "Deal Threads ICP Score", "Deal Threads ICP score from 0 to 100."),
    stringProperty("deal_threads_lead_profile_id", "Deal Threads Lead Profile ID", "Internal Deal Threads lead profile ID."),
    textAreaProperty("deal_threads_next_action", "Deal Threads Next Action", "Recommended sales action generated by Deal Threads.")
  ]
};

export function hubSpotMode() {
  return process.env.HUBSPOT_TOKEN ? "live" : "stubbed";
}

export function requiredHubSpotProperties() {
  return structuredClone(propertyDefinitions);
}

export function hubSpotSyncPreview(lead) {
  const blockers = hubSpotSyncBlockers(lead);
  const contactPropertiesForLead = contactProperties(lead);
  const companyPropertiesForLead = companyProperties(lead);
  const noteBody = hubSpotNoteBody(lead);

  return {
    generated_at: new Date().toISOString(),
    mode: hubSpotMode(),
    token_configured: Boolean(process.env.HUBSPOT_TOKEN),
    base_url: HUBSPOT_BASE_URL,
    eligible: blockers.length === 0,
    blockers,
    dry_run: !process.env.HUBSPOT_TOKEN,
    operations: [
      {
        object_type: "contacts",
        operation: lead.contact?.email ? "upsert_by_email" : "blocked_missing_email",
        lookup_property: "email",
        lookup_value: lead.contact?.email || null,
        properties: contactPropertiesForLead
      },
      {
        object_type: "companies",
        operation: lead.company?.domain ? "upsert_by_domain" : "create_without_domain",
        lookup_property: lead.company?.domain ? "domain" : null,
        lookup_value: lead.company?.domain || null,
        properties: companyPropertiesForLead
      },
      {
        object_type: "notes",
        operation: "create_note_after_contact_sync",
        associations: ["contact", "company_if_available"],
        properties: {
          hs_timestamp: "<sync-time>",
          hs_note_body: noteBody
        }
      }
    ],
    required_properties: requiredHubSpotProperties()
  };
}

export async function checkHubSpotProperties({ createMissing = false } = {}) {
  const definitions = flattenDefinitions();

  if (!process.env.HUBSPOT_TOKEN) {
    return {
      mode: "stubbed",
      createMissing,
      checkedAt: new Date().toISOString(),
      summary: {
        required: definitions.length,
        existing: 0,
        missing: definitions.length,
        created: 0,
        failed: 0
      },
      properties: definitions.map(({ objectType, definition }) => ({
        objectType,
        name: definition.name,
        label: definition.label,
        status: "token_missing",
        action: createMissing ? "would_create" : "would_check"
      }))
    };
  }

  const properties = [];
  const scopeErrorsByObjectType = new Map();

  for (const item of definitions) {
    const { objectType, definition } = item;
    const scopeError = scopeErrorsByObjectType.get(objectType);
    if (scopeError) {
      properties.push(scopeMissingProperty(objectType, definition, scopeError));
      continue;
    }

    let existing;
    try {
      existing = await getPropertyIfExists(objectType, definition.name);
    } catch (error) {
      if (isHubSpotScopeError(error)) {
        scopeErrorsByObjectType.set(objectType, error);
        properties.push(scopeMissingProperty(objectType, definition, error));
        continue;
      }
      properties.push({
        objectType,
        name: definition.name,
        label: definition.label,
        status: "failed",
        error: safeHubSpotErrorMessage(error)
      });
      continue;
    }

    if (existing) {
      properties.push({
        objectType,
        name: definition.name,
        label: definition.label,
        status: "existing",
        hubspotType: existing.type,
        hubspotFieldType: existing.fieldType
      });
      continue;
    }

    if (!createMissing) {
      properties.push({
        objectType,
        name: definition.name,
        label: definition.label,
        status: "missing"
      });
      continue;
    }

    try {
      const created = await createProperty(objectType, definition);
      properties.push({
        objectType,
        name: definition.name,
        label: definition.label,
        status: "created",
        hubspotType: created.type,
        hubspotFieldType: created.fieldType
      });
    } catch (error) {
      if (isHubSpotScopeError(error)) {
        scopeErrorsByObjectType.set(objectType, error);
        properties.push(scopeMissingProperty(objectType, definition, error));
        continue;
      }
      properties.push({
        objectType,
        name: definition.name,
        label: definition.label,
        status: "failed",
        error: safeHubSpotErrorMessage(error)
      });
    }
  }

  return {
    mode: "live",
    createMissing,
    checkedAt: new Date().toISOString(),
    summary: summarizeProperties(properties),
    properties
  };
}

export async function syncLeadToHubSpot(lead) {
  const preview = hubSpotSyncPreview(lead);
  if (preview.blockers.length) {
    return {
      provider: "hubspot",
      sync_status: "failed",
      contact_id: null,
      company_id: null,
      deal_id: null,
      last_error: `HubSpot sync blocked: ${preview.blockers.join(", ")}`,
      synced_at: null,
      mode: hubSpotMode()
    };
  }

  if (!process.env.HUBSPOT_TOKEN) {
    return {
      provider: "hubspot",
      sync_status: "stubbed",
      contact_id: null,
      company_id: null,
      deal_id: null,
      last_error: "HUBSPOT_TOKEN not set in local development",
      synced_at: null,
      mode: "stubbed"
    };
  }

  try {
    const contact = await upsertContact(lead);
    const company = await upsertCompany(lead);

    if (contact.id && company.id) {
      await associateContactToCompany(contact.id, company.id);
    }

    if (contact.id) {
      await createNote(lead, contact.id, company.id);
    }

    return {
      provider: "hubspot",
      sync_status: "synced",
      contact_id: contact.id || null,
      company_id: company.id || null,
      deal_id: null,
      last_error: null,
      synced_at: new Date().toISOString(),
      mode: "live"
    };
  } catch (error) {
    return {
      provider: "hubspot",
      sync_status: "failed",
      contact_id: null,
      company_id: null,
      deal_id: null,
      last_error: error.message,
      synced_at: null,
      mode: "live"
    };
  }
}

function hubSpotSyncBlockers(lead) {
  const blockers = [];
  if (!lead?.contact?.email) blockers.push("missing_contact_email");
  if (!lead?.company?.name && !lead?.company?.domain) blockers.push("missing_company_identity");
  if (!lead?.summary?.rep_summary) blockers.push("missing_rep_summary");
  return blockers;
}

async function upsertContact(lead) {
  const existing = await findObjectByProperty("contacts", "email", lead.contact.email);
  const properties = contactProperties(lead);

  if (existing?.id) {
    await hubSpotRequest(`/crm/v3/objects/contacts/${existing.id}`, {
      method: "PATCH",
      body: { properties }
    });
    return existing;
  }

  return hubSpotRequest("/crm/v3/objects/contacts", {
    method: "POST",
    body: { properties }
  });
}

async function upsertCompany(lead) {
  const domain = lead.company.domain;
  const existing = domain ? await findObjectByProperty("companies", "domain", domain) : null;
  const properties = companyProperties(lead);

  if (existing?.id) {
    await hubSpotRequest(`/crm/v3/objects/companies/${existing.id}`, {
      method: "PATCH",
      body: { properties }
    });
    return existing;
  }

  return hubSpotRequest("/crm/v3/objects/companies", {
    method: "POST",
    body: { properties }
  });
}

async function findObjectByProperty(objectType, propertyName, value) {
  if (!value) return null;

  const result = await hubSpotRequest(`/crm/v3/objects/${objectType}/search`, {
    method: "POST",
    body: {
      filterGroups: [
        {
          filters: [
            {
              propertyName,
              operator: "EQ",
              value
            }
          ]
        }
      ],
      properties: [propertyName],
      limit: 1
    }
  });

  return result.results?.[0] || null;
}

async function getPropertyIfExists(objectType, propertyName) {
  try {
    return await hubSpotRequest(`/crm/v3/properties/${objectType}/${propertyName}`);
  } catch (error) {
    if (error.status === 404) return null;
    throw error;
  }
}

async function createProperty(objectType, definition) {
  return hubSpotRequest(`/crm/v3/properties/${objectType}`, {
    method: "POST",
    body: definition
  });
}

async function associateContactToCompany(contactId, companyId) {
  return hubSpotRequest(`/crm/v3/objects/contacts/${contactId}/associations/companies/${companyId}/contact_to_company`, {
    method: "PUT"
  });
}

async function createNote(lead, contactId, companyId) {
  const associations = [
    {
      to: { id: contactId },
      types: [{ associationCategory: "HUBSPOT_DEFINED", associationTypeId: 202 }]
    }
  ];

  if (companyId) {
    associations.push({
      to: { id: companyId },
      types: [{ associationCategory: "HUBSPOT_DEFINED", associationTypeId: 190 }]
    });
  }

  return hubSpotRequest("/crm/v3/objects/notes", {
    method: "POST",
    body: {
      properties: {
        hs_timestamp: new Date().toISOString(),
        hs_note_body: hubSpotNoteBody(lead)
      },
      associations
    }
  });
}

function scopeMissingProperty(objectType, definition, error) {
  return {
    objectType,
    name: definition.name,
    label: definition.label,
    status: "scope_missing",
    action: "skipped_requires_scope",
    requiredScopes: requiredScopesForObjectType(objectType),
    error: safeHubSpotErrorMessage(error)
  };
}

function requiredScopesForObjectType(objectType) {
  if (objectType === "contacts") return ["crm.objects.contacts.read", "crm.objects.contacts.write"];
  if (objectType === "companies") return ["crm.objects.companies.read", "crm.objects.companies.write"];
  if (objectType === "deals") return ["crm.objects.deals.read", "crm.objects.deals.write"];
  return [];
}

function isHubSpotScopeError(error) {
  if (error?.status !== 403) return false;
  const text = `${error.message || ""} ${JSON.stringify(error.payload || {})}`;
  return /scope|permission|permissions|ObjectTypeId|MISSING_SCOPES/i.test(text);
}

function safeHubSpotErrorMessage(error) {
  return String(error?.message || "HubSpot request failed.").replace(/pat-na[0-9]-[A-Za-z0-9_-]+/g, "[redacted-hubspot-token]");
}

function contactProperties(lead) {
  const [firstName, ...lastParts] = String(lead.contact.name || "").trim().split(/\s+/).filter(Boolean);
  return cleanProperties({
    email: lead.contact.email,
    firstname: firstName,
    lastname: lastParts.join(" "),
    phone: lead.contact.phone,
    jobtitle: lead.contact.role,
    deal_threads_authority_signal: lead.contact.authority_signal,
    deal_threads_timeline: lead.qualification.timeline,
    deal_threads_budget_status: lead.qualification.budget_status,
    deal_threads_budget_range: lead.qualification.budget_range,
    deal_threads_business_need: lead.qualification.business_need,
    deal_threads_pain_point: lead.qualification.pain_point,
    deal_threads_icp_score: String(lead.score.icp_fit),
    deal_threads_priority: lead.score.priority,
    deal_threads_next_action: lead.routing.recommended_next_action,
    deal_threads_source_page: lead.source.page_url,
    deal_threads_utm_campaign: lead.source.utm_campaign,
    deal_threads_sync_status: "synced",
    deal_threads_lead_profile_id: lead.id,
    deal_threads_conversation_id: lead.conversation_id,
    deal_threads_last_synced_at: new Date().toISOString()
  });
}

function companyProperties(lead) {
  return cleanProperties({
    domain: lead.company.domain,
    name: lead.company.name,
    industry: lead.company.industry === "unknown" ? undefined : lead.company.industry,
    deal_threads_employee_range: lead.company.employee_range,
    deal_threads_revenue_range: lead.company.revenue_range,
    deal_threads_tech_stack: lead.enrichment.tech_stack?.map((item) => item.value).join("; "),
    deal_threads_recent_funding: lead.enrichment.funding_events?.map((event) => event.value || event).join("; "),
    deal_threads_icp_segment: lead.score.segment,
    deal_threads_enrichment_status: lead.enrichment.status,
    deal_threads_enrichment_confidence: String(lead.enrichment.confidence)
  });
}

function hubSpotNoteBody(lead) {
  const list = (items) => (items.length ? items.map((item) => `- ${item}`).join("\n") : "- None");

  return [
    "Deal Threads AI Lead Profile",
    "",
    `Priority: ${lead.score.priority} (${lead.score.icp_fit}/100)`,
    `Recommended next action: ${lead.routing.recommended_next_action}`,
    "",
    "Intent:",
    lead.summary.rep_summary,
    "",
    "Visitor-provided facts:",
    list(lead.summary.visitor_facts),
    "",
    "Enriched context:",
    list(lead.summary.enriched_facts),
    "",
    "Watchouts:",
    list(lead.summary.watchouts),
    "",
    `Deal Threads profile ID: ${lead.id}`
  ].join("\n");
}

function cleanProperties(properties) {
  return Object.fromEntries(
    Object.entries(properties).filter(([, value]) => value !== undefined && value !== null && value !== "")
  );
}

async function hubSpotRequest(path, options = {}) {
  const response = await fetch(`${HUBSPOT_BASE_URL}${path}`, {
    method: options.method || "GET",
    headers: {
      authorization: `Bearer ${process.env.HUBSPOT_TOKEN}`,
      "content-type": "application/json"
    },
    body: options.body ? JSON.stringify(options.body) : undefined
  });

  const text = await response.text();
  const payload = text ? JSON.parse(text) : {};

  if (!response.ok) {
    const message = payload.message || payload.error || `HubSpot request failed with ${response.status}`;
    const error = new Error(message);
    error.status = response.status;
    error.payload = payload;
    throw error;
  }

  return payload;
}

function flattenDefinitions() {
  return Object.entries(propertyDefinitions).flatMap(([objectType, definitions]) =>
    definitions.map((definition) => ({
      objectType,
      definition: {
        ...definition,
        groupName: defaultPropertyGroup(objectType)
      }
    }))
  );
}

function defaultPropertyGroup(objectType) {
  if (objectType === "contacts") return "contactinformation";
  if (objectType === "companies") return "companyinformation";
  if (objectType === "deals") return "dealinformation";
  return "deal_threads_information";
}

function summarizeProperties(properties) {
  const summary = {
    required: properties.length,
    existing: 0,
    missing: 0,
    created: 0,
    failed: 0,
    inaccessible: 0,
    by_object_type: {}
  };

  for (const property of properties) {
    summary.by_object_type[property.objectType] ||= {
      required: 0,
      existing: 0,
      missing: 0,
      created: 0,
      failed: 0,
      inaccessible: 0
    };
    const objectSummary = summary.by_object_type[property.objectType];
    objectSummary.required += 1;

    if (property.status === "existing") summary.existing += 1;
    if (property.status === "missing" || property.status === "token_missing") summary.missing += 1;
    if (property.status === "created") summary.created += 1;
    if (property.status === "failed") summary.failed += 1;
    if (property.status === "scope_missing") summary.inaccessible += 1;

    if (property.status === "existing") objectSummary.existing += 1;
    if (property.status === "missing" || property.status === "token_missing") objectSummary.missing += 1;
    if (property.status === "created") objectSummary.created += 1;
    if (property.status === "failed") objectSummary.failed += 1;
    if (property.status === "scope_missing") objectSummary.inaccessible += 1;
  }

  return summary;
}

function baseProperty(name, label, description, type, fieldType) {
  return {
    name,
    label,
    description,
    groupName: "deal_threads_information",
    type,
    fieldType,
    formField: false
  };
}

function stringProperty(name, label, description) {
  return baseProperty(name, label, description, "string", "text");
}

function textAreaProperty(name, label, description) {
  return baseProperty(name, label, description, "string", "textarea");
}

function numberProperty(name, label, description) {
  return baseProperty(name, label, description, "number", "number");
}

function enumProperty(name, label, description, options) {
  return {
    ...baseProperty(name, label, description, "enumeration", "select"),
    options: options.map(([labelValue, value], displayOrder) => ({
      label: labelValue,
      value,
      displayOrder,
      hidden: false
    }))
  };
}
