#!/usr/bin/env python3
"""Render the oloxa-content-factory workflow JSON into a publish-ready weekly calendar.

Deterministic (no LLM). Reads the workflow result (or its task envelope),
writes a dated content calendar markdown: per-day graded LinkedIn post (copy-paste),
short-form script, comment targets, and grader scores. Drafts only - nothing posts.

Usage:
  python3 content_to_md.py <input_json> <output_md> [week_of]
"""
import html
import json
import sys


def u(s):
    return html.unescape(s) if isinstance(s, str) else (s or "")


def day_block(p):
    sc = p.get("scores", {}) or {}
    post = p.get("post", {}) or {}
    flag = "✅" if (p.get("overall") or 0) >= 8.5 else "⚠️"
    out = []
    out.append(f"## {flag} {p.get('day')} — {u(p.get('pillar'))}  ·  score {p.get('overall')}/10")
    out.append(f"_Audience:_ {u(p.get('audience'))}  ·  _Words:_ {post.get('word_count','?')}\n")
    out.append("**LinkedIn post** (copy-paste):")
    out.append(f"```\n{u(post.get('full_post'))}\n```")
    if post.get("short_form_script"):
        out.append(f"**Short-form script** (20-35s):\n```\n{u(post.get('short_form_script'))}\n```")
    cts = post.get("comment_targets", []) or []
    if cts:
        out.append("**Comment targets that day:**")
        for c in cts:
            out.append(f"- {u(c)}")
    sc_line = " · ".join(f"{k}:{v}" for k, v in sc.items())
    out.append(f"\n_Grader:_ {sc_line}")
    tells = p.get("ai_tells_found", []) or []
    changes = p.get("changes_made", []) or []
    if tells:
        out.append(f"_AI tells removed:_ {', '.join(u(t) for t in tells)}")
    if changes:
        out.append(f"_Edits:_ {', '.join(u(c) for c in changes[:4])}")
    out.append("\n---\n")
    return "\n".join(out)


def main():
    if len(sys.argv) < 3:
        print(__doc__); sys.exit(1)
    with open(sys.argv[1], encoding="utf-8") as f:
        data = json.load(f)
    if "posts" not in data and isinstance(data.get("result"), dict):
        data = data["result"]
    posts = data.get("posts", [])
    week = sys.argv[3] if len(sys.argv) > 3 else data.get("week_of", "")

    order = {d: i for i, d in enumerate(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"])}
    posts.sort(key=lambda p: order.get(p.get("day"), 9))

    below = [p for p in posts if (p.get("overall") or 0) < 8.5]
    L = [f"# Oloxa Content Calendar — week of {week}\n"]
    L.append("> Generated by the `oloxa-content-factory` workflow (draft → grade vs Content Grader → strip AI tells). "
             "**Drafts only — nothing has been posted.** Review, then publish manually. "
             f"Avg score: {data.get('avg_score','?')}/10.\n")
    L.append(f"**{len(posts)} posts** · {len(posts)-len(below)} at/above 8.5 bar"
             + (f" · ⚠️ {len(below)} below bar (review): {', '.join(p.get('day') for p in below)}" if below else "")
             + "\n\n---\n")
    for p in posts:
        L.append(day_block(p))
    L.append("### Daily non-negotiable\n10 thoughtful comments/day on the targets above (see Commenting Playbook). "
             "Log any buyer language into the GTM Brain; add any inbound lead to the Outcome Tracker.")

    with open(sys.argv[2], "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print(f"Wrote {sys.argv[2]} ({len(posts)} posts, avg {data.get('avg_score','?')}/10, {len(below)} below bar)")


if __name__ == "__main__":
    main()
