#!/usr/bin/env python3
"""Render an Oloxa battlecard workflow JSON result into a human-readable markdown briefing.

Usage:
    python3 battlecards_to_md.py <input_json> <output_md> [date]

Reads the JSON returned by the 'oloxa-outbound-battlecards' dynamic workflow
(or the task envelope wrapping it) and writes a dated briefing: a triage table
(auto-classified SEND / REVIEW / HOLD) plus one full battlecard section per lead,
sorted by rank. Drafts only - nothing is sent.
"""
import html
import json
import sys

REFRAME_KW = [
    "direct lender", "not a broker", "balance-sheet", "single-lender",
    "single-source", "single source", "lender-side", "residential retail",
    "off-profile", "does not apply",
]


def u(x):
    return html.unescape(x) if isinstance(x, str) else ("" if x is None else x)


def action_for(card):
    r = card.get("research", {}) or {}
    conf = (r.get("confidence") or "").upper()
    verified = r.get("signal_verified")
    rec = (r.get("signal_recency") or "").lower()
    flags = " ".join(r.get("red_flags", []) or []).lower()
    if conf == "LOW" or verified is False:
        return ("HOLD", "HOLD")
    if any(k in flags for k in REFRAME_KW):
        return ("REVIEW", "REVIEW")
    if conf == "MEDIUM" and ("unverif" in rec or rec == "older"):
        return ("REVIEW", "REVIEW")
    return ("SEND", "SEND")


EMOJI = {"SEND": "✅", "REVIEW": "⚠️", "HOLD": "⏸️"}


def section(card):
    r = card.get("research", {}) or {}
    b = card.get("battlecard", {}) or {}
    obj = b.get("top_objection", {}) or {}
    act, _ = action_for(card)
    em = EMOJI[act]
    out = []
    out.append(
        f"## {em} {card.get('rank')}. {u(card.get('name'))} — {u(card.get('company'))} "
        f"· {card.get('market')} · {card.get('signal')} "
        f"· {r.get('confidence')} · {u(card.get('assigned_to'))} · **{act}**"
    )
    qa = "✅ pass" if card.get("qa_pass") else "⚠️ fixed"
    out.append(
        f"`{u(card.get('email'))}` · [LinkedIn]({u(card.get('linkedin_url'))}) "
        f"· QA: {qa}\n"
    )
    out.append("**Evidence (verified / not):**")
    for e in r.get("evidence", []) or []:
        out.append(f"- {u(e)}")
    out.append(f"\n**Pain hypothesis:** {u(r.get('pain_hypothesis'))}")
    out.append(f"\n**Why now:** {u(r.get('why_now'))}")
    rf = r.get("red_flags", []) or []
    if rf:
        out.append("\n**Red flags:**")
        for f in rf:
            out.append(f"- {u(f)}")
    qv = card.get("qa_violations", []) or []
    if qv:
        out.append("\n**QA fixes applied:**")
        for v in qv:
            out.append(f"- {u(v)}")
    out.append(f"\n**Recommended sequence:** {u(b.get('recommended_sequence'))}\n")
    out.append(f"**LinkedIn connect**\n{u(b.get('linkedin_connect_note'))}\n")
    out.append(f"**LinkedIn DM**\n{u(b.get('linkedin_dm'))}\n")
    out.append(f"**Email** · *{u(b.get('email_subject'))}*\n{u(b.get('email_body'))}\n")
    out.append(f"**Cold call**\n{u(b.get('cold_call_opener'))}\n")
    out.append(f"**Voicemail**\n{u(b.get('voicemail'))}\n")
    out.append(f"**SMS**\n{u(b.get('sms'))}\n")
    out.append(f"**Follow-up 1**\n{u(b.get('follow_up_1'))}\n")
    out.append(f"**Follow-up 2**\n{u(b.get('follow_up_2'))}\n")
    out.append(
        f"**Top objection** — *{u(obj.get('objection'))}*\n\n{u(obj.get('response'))}"
    )
    out.append("\n---\n")
    return "\n".join(out)


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    with open(sys.argv[1], "r", encoding="utf-8") as f:
        data = json.load(f)
    if "cards" not in data and isinstance(data.get("result"), dict):
        data = data["result"]
    cards = sorted(data.get("cards", []), key=lambda c: c.get("rank", 999))
    date = sys.argv[3] if len(sys.argv) > 3 else data.get("date", "")

    counts = {"SEND": 0, "REVIEW": 0, "HOLD": 0}
    for c in cards:
        counts[action_for(c)[0]] += 1

    L = []
    L.append(f"# Daily Outbound Battlecards — {date}\n")
    L.append(
        "> Generated by the `oloxa-outbound-battlecards` dynamic workflow "
        "(verify signal → multi-channel copy → adversarial brand-QA). "
        "**Drafts only. Nothing has been sent.** Machine-readable: "
        f"`Oloxa_Battlecards_{date}.csv`.\n"
    )
    L.append(
        f"**{len(cards)} leads** — {EMOJI['SEND']} {counts['SEND']} send "
        f"· {EMOJI['REVIEW']} {counts['REVIEW']} review/reframe "
        f"· {EMOJI['HOLD']} {counts['HOLD']} hold\n"
    )
    L.append("## Triage\n")
    L.append("| # | Lead | Company | Mkt | Signal | Conf | Verified | Recency | QA | Action |")
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    for c in cards:
        act, _ = action_for(c)
        r = c.get("research", {}) or {}
        L.append(
            f"| {c.get('rank')} | {u(c.get('name'))} | {u(c.get('company'))} | "
            f"{c.get('market')} | {c.get('signal')} | {r.get('confidence')} | "
            f"{'yes' if r.get('signal_verified') else '**NO**'} | "
            f"{u(r.get('signal_recency',''))} | "
            f"{'pass' if c.get('qa_pass') else 'fixed'} | {EMOJI[act]} {act} |"
        )
    L.append("\n*Action rule: HOLD = unverified/low-confidence signal; REVIEW = reframe needed "
             "(model mismatch) or soft why-now; SEND = verified + clean.*\n\n---\n")
    for c in cards:
        L.append(section(c))

    with open(sys.argv[2], "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print(f"Wrote {len(cards)} battlecards to {sys.argv[2]} "
          f"(send {counts['SEND']} / review {counts['REVIEW']} / hold {counts['HOLD']})")


if __name__ == "__main__":
    main()
